### ISSUE TITLE
meta/documentation: Docker built using GitHub Actions?

### ISSUE THREAD

**Issue by kc9jud** [openwall/john-packages#20]
Just to clarify, does this repository use GitHub actions to build the Docker images? [`readme.md#docker-image`](https://github.com/openwall/john-packages/blob/master/readme.md#docker-image) has a note "Delivered using GitHub Actions", but the [flow chart](https://github.com/openwall/john-packages/blob/master/graph.mermaid) says that it's using Circle CI.

**Comment by claudioandre-br** [comment]
Oh! The flowchart is about the testing and CI process using Docker images in Circle CI (the delivered Docker image is included in these tests). It's not about the CD process (the software delivery itself).

The CD process follows the CI, but is not mandatory/automatic after the CI. It involves Launchpad, GitHub Actions, Flatpak Hub, ...

**Comment by claudioandre-br** [comment]
Nothing to do here.
