### ISSUE TITLE
compress-raw-lzma-perl No longer exists

### ISSUE THREAD

**Issue by MiloAC1** [openwall/john-packages#364]
## I dont think I need to list steps to reproduce, just that a large amount of commands are not functional as you can no longer install the old packages

**Comment by claudioandre-br** [comment]
Thanks for reporting.

I'm afraid I don't understand your complaint here. What I understood is:
- you say the `7z2john` command doesn't work;
   - I just tested using a Ubuntu 24.04 and it worked (after a `sudo apt-get install -y libcompress-raw-lzma-perl`).
- could you clarify exactly what no longer works?

What are the "large amounts of commands" that are not working? Could you add examples?
