### ISSUE TITLE
Create an Android build

### ISSUE THREAD

**Issue by claudioandre-br** [openwall/john-packages#43]
No apk:

- To create an apk package I need several files created by Android Studio. A lot.
- And I need to add support for CMake.
    
I tested the build and created a zip for Android X86 and another for Android ARM.

**Comment by solardiz** [comment]
By "attaching all the project files" do you mean every C source file in JtR tree? No good way to have something like our build-time "plugins" system that we use in autoconf'ed builds?

**Comment by claudioandre-br** [comment]
> By "attaching all the project files" do you mean every C source file in JtR tree? No good way to have something like our build-time "plugins" system that we use in autoconf'ed builds?

No. I just need some project and glade files.

Actually, there's no need to worry about the JtR source tree, any C "hello world" is ok for me. I will do the real build inside CI.

But, I have a question:
- Would john's build work in Android Studio if I want to target a "phone"? I mean, I would need to configure specifying something as a target architeture?
- I think the Android Studio wizard and project files will answer this.

**Comment by claudioandre-br** [comment]
Never mind, a lot of files would need to be created, including adding support for CMake.
