### ISSUE TITLE
[BUG]: the logo looks "blurry"

### ISSUE THREAD

**Issue by claudioandre-br** [openwall/john-packages#476]
### Which version of the application are you using?

1.9J1+2404, latest bleeding

### Description of the bug

Our logo looks blurry; we can and should improve that. 

This is what we have as a proposal. Let's leave it open for a week, maybe other proposals will come up:

![com openwall John](https://github.com/user-attachments/assets/110e44a7-ab47-4ab1-889a-913f50ab8044)

### Steps To Reproduce

Current situation:

![original](https://github.com/user-attachments/assets/ca56f3cb-840f-4d31-a89e-5cbbb93e84a1)

**Comment by solardiz** [comment]
Where do we use that blurry logo?

FWIW, here's a hi-res black-and-white version we use with "in the cloud" offering (link as set up by AWS internally): https://d7umqicpi7263.cloudfront.net/img/product/a23edc77-717f-4357-b252-560bdaeecad7.com/7250a133b41b5107132e31cbe2c243d2

**Comment by claudioandre-br** [comment]
> Where do we use that blurry logo?

In https://github.com/openwall/john-packages/blob/main/deploy/metadata/com.openwall.John.png it becomes the desktop icon for installed applications.

![image](https://github.com/user-attachments/assets/31733d2d-42a9-48de-9ac2-1237cb3cb328)

**Comment by claudioandre-br** [comment]
So, a second proposal would be (256x256, tiny transparent border):

![7250a133b41b5107132e31cbe2c243d2](https://github.com/user-attachments/assets/bf6c30f6-628b-4000-b85e-5056c3db061c)   ![7250a133b41b5107132e31cbe2c243d2](https://github.com/user-attachments/assets/b9fcee1d-be13-4c00-a72d-d0a70f84a8ee)

**Comment by solardiz** [comment]
For an app icon, I think your first proposal is fine. The b&w would probably look worse along with other icons in your example.

I guess the previous icon is low resolution and blurry because one of us took it from a t-shirt "photo". I probably have the originals of those logos somewhere, I may dig them up later.

**Comment by claudioandre-br** [comment]
- Lean, clean, simple: the first is the winner;
- The 2nd is bigger (just that);
- The 3rd is a kind of nice stamp.

![352850594-110e44a7-ab47-4ab1-889a-913f50ab8044](https://github.com/user-attachments/assets/5613cbc7-12c1-4922-a705-cff529ff3907) ![strong](https://github.com/user-attachments/assets/cb26ca92-0082-46af-a84a-8f281d6a7219) ![old-stuff](https://github.com/user-attachments/assets/5182a09c-6f40-48ad-bd11-d0be93f8b97d)
