### ISSUE TITLE
Move Docker images to GitHub Packages

### ISSUE THREAD

**Issue by claudioandre-br** [openwall/john-packages#5]
Due to pull rate limit imposed by Docker Hub, I'm looking for better places to host Docker images. I'm planing to move JtR Docker images  from Docker Hub to GitHub Repository. It seems one configuration is missing.

> denied: failed_precondition: Improved container support has not been enabled for 'openwall'. Learn more: https://docs.github.com/packages/getting-started-with-github-container-registry/enabling-improved-container-support

@solardiz, could you please enable it? There is no cost involved; the images will be public and docs says there are no fees for public images.

**Comment by solardiz** [comment]
@claudioandre-br I've just enabled this for the org.

**Comment by claudioandre-br** [comment]
Done: 
* https://github.com/orgs/openwall/packages/container/package/john
* `docker pull ghcr.io/openwall/john:v1.9.0j1`
* `docker pull ghcr.io/openwall/john:v1.9.0j2`

Thanks Solar.
