### ISSUE TITLE
Add OpenSSF Best Practices

### ISSUE THREAD

**Issue by claudioandre-br** [openwall/john-packages#61]
**1. Is your feature request related to a problem? Please describe.**

Audit this repository as seen at https://bestpractices.coreinfrastructure.org/projects/7525
![image](https://github.com/openwall/john-packages/assets/1702923/4a3ad814-1454-478b-a06d-92d36d4d39b8)

**2. Describe the solution you'd like**

Add the checklist for the repository practices.

**3. Additional context**

[OpenSSF Best Practices](https://bestpractices.coreinfrastructure.org/en)
****
@solardiz , when you have some free time could you please accept the access request you (probably) received some days ago?
- from Github and me to autorize codefactor to access the repos.

This will authorize codefactor (https://www.codefactor.io/repository/github/openwall/john-packages) to run and scan all commits.

**Comment by solardiz** [comment]
> accept the access request you (probably) received some days ago?

Accepted.

**Comment by claudioandre-br** [comment]
Thank you.

**Comment by claudioandre-br** [comment]
Done.

**Comment by solardiz** [comment]
@claudioandre-br Somehow today I got the codefactor.io authorization again, and approved it again. What's worse, I don't see it among the approved third-party apps - I only see Azure Pipelines and Travis CI there. Also, the authorization request is worded as granting access to "private resources", which doesn't sound like something we actually want here (what private resources? we have no private repos).

Here's what those e-mails say:

```
Subject: [GitHub] Third-party application approval request for "Openwall"

@claudioandre-br has requested approval for a third-party application to access "Openwall" organization resources via the GitHub API:


  "codefactor.io" from CodeFactor


Until it is approved, this application will have no access to private resources and will have read-only access to public resources belonging to your organization.
```

**Comment by claudioandre-br** [comment]
> Somehow today I got the codefactor.io authorization again, 

I saw this happening more than once (you need to authorize twice). There are two connectors Github x Codefactor.
* https://github.com/settings/connections/applications/4194d7d196308e89f706 (me)
* https://github.com/settings/connections/applications/14bba86d5cba01f3c60f (me again)

Don't ask why, I don't kwow the answer. Both links to my settings(?) page.

Now codefactor badge and repo grade are updated (so, things are fully working). It wasn't some time ago.
****
I guess we can use codefactor in private repositories. Since they don't exist, we are safe. 

If you create one later, we can review or revoke the setting.

We can also revoke the access now and see what happens (it only needs to create a webhook once). No need to request to go to your medical doctor with you.

**Comment by claudioandre-br** [comment]
The remaining issues are listed below [1]:

![image](https://github.com/openwall/john-packages/assets/1702923/c5c56dc2-1ea3-41c7-b74c-12987bafeaa7)

[1] Ok, the content present here (the project itself) is simple. 
 - these erros will stay "as is" for a while.
- linters and static analysers are happy.
- there is no solution for the first two.

**Comment by solardiz** [comment]
> There are two connectors Github x Codefactor.

@claudioandre-br I hope those links you posted are not security-sensitive, but just in case we might want to remove them from here. The IDs in them appear specific to your account anyway, so not useful here.

**Comment by claudioandre-br** [comment]
> > There are two connectors Github x Codefactor.
> 
> @claudioandre-br I hope those links you posted are not security-sensitive, but just in case we might want to remove them from here. The IDs in them appear specific to your account anyway, so not useful here.

Don't worry, if Github is drunk and you can access them, you need to provide 2FA/MFA.

**Comment by solardiz** [comment]
> Don't worry, if Github is drunk and you can access them, you need to provide 2FA/MFA.

I meant that attacks on web apps often involve tricky and unexpected interactions of different things, and a copy of some normally secret material, even if not sufficient on its own, could turn out to be precisely the missing bit for a successful attack. But I don't worry much.

**Comment by claudioandre-br** [comment]
I removed it (also from history).

**Comment by claudioandre-br** [comment]
Follow up:

> the authorization request is worded as granting access to "private resources", which doesn't sound like something we actually want here (what private resources? we have no private repos).

Codefactor.io is an OAuth application. It's nothing or everything. I think this will get better some day; we all agree that the request is invasive.
****
An evolution:
On the other hand, Github Apps are better and allow us to narrow down the list of repositories properly:

![Captura de tela de 2023-07-05 15-54-59](https://github.com/openwall/john-packages/assets/1702923/3f013596-8600-4567-b3ed-78de9787abc0)

Above, an example of another Github app (which does something else). Newer and better. 

The wording is the same, but you can adjust what is shared.

**Comment by solardiz** [comment]
@claudioandre-br Do you suggest any specific action now? Do you need anything from me?

**Comment by claudioandre-br** [comment]
No, thanks.

Github should enforce best practices and all these companies (codefactor is the focus now) should invest in improvements.

**Comment by solardiz** [comment]
@claudioandre-br I mean, do we possibly need to revoke permissions? If you're not going to use this app.

**Comment by claudioandre-br** [comment]
I'm afraid it will stop working properly sometime if we revoke the permissions. But, if you feel uncomfortable with the current permissions, I think you can revoke without removing.

I enjoy the checking they are doing.

**Comment by solardiz** [comment]
@claudioandre-br Oh, OK. I think I misinterpreted some of what you wrote. I'll leave things as they are for now.
