### ISSUE TITLE
john-avx2.exe

### ISSUE THREAD

**Issue by coloboxp** [openwall/john-packages#7]
Hi Andre

I could find only the non-omp verson of john-avx2.exe. Do you happen to have the compiled version for windows using omp and avx2 ?

best regards

**Comment by claudioandre-br** [comment]
I think you (downloaded and) are using the stable version of the package: `x64_win.zip` or `x32_win.zip`.

* In this case, `john.exe` is the file that has OMP and AVX2 enabled.

In fact, unless you want to compare, there is no need to choose which binary to run, it automatically selects to the best choice for your hardware.

**Comment by coloboxp** [comment]
Oh ok! Thank you

Obrigado pela ajuda
