### ISSUE TITLE
Drop donation badges/links

### ISSUE THREAD

**Issue by solardiz** [openwall/john-packages#74]
I just noticed that we have some donation badges/links in here. Looks like two lead nowhere, and one to the 0-Day Clothing store for Openwall/JtR apparel. The latter used to include a $10 donation in t-shirt prices that we intended to use for sending free t-shirts to project contributors, which we once did, but we haven't actually done so again for years (maybe wrongly!), leaving these funds with 0-Day Clothing. It looks like they no longer collect those donations now (quite reasonably). I should probably follow up with them on that, but anyhow we're not currently collecting any donations, so shouldn't currently have such badges/links.

I may enable GitHub Sponsors later, but even if so I was thinking of requesting support only from organizations (so with pre-tax money), not from individuals.

**Comment by claudioandre-br** [comment]
There is no link, just the reminder (the image). 

The idea is that people try to figure out how to donate (but the Openwall donation page is down). Anyway, at least using Sponsors, something should be available by default.

**Comment by solardiz** [comment]
> at least using Sponsors, something should be available by default.

Maybe, but right now it is not, so it's weird to be reminding people of something they currently cannot do.

**Comment by solardiz** [comment]
Besides the badges, there's also https://github.com/openwall/john-packages/blob/5e9afa4fa41079ad5b72b70094240fe97eaf22aa/deploy/metadata/com.openwall.John.appdata.xml#L37
